### ISSUE TITLE
Folder won't move from root folder to subfolder

### ISSUE THREAD

**Issue by frenchfilm** [filebrowser/filebrowser#1434]
**Description**

Trying to move a folder from root folder to subfolder
**Expected behaviour**

Folder should move no problem. Many other folders moved without issue
**What is happening instead?**

500 internal server error message
**Additional context**

![image](https://user-images.githubusercontent.com/39890330/121886925-5d1ba700-cd16-11eb-9ed3-02304238fed7.png)

**How to reproduce?**

Don't know
**Files**

**Comment by ramiresviana** [comment]
Manipulating directories and file with names containing special characters was causing errors. This is already fixed and should be available on the next version release.

**Comment by AshDevFr** [comment]
I still experience the issue, when is the next release ?

**Comment by frenchfilm** [comment]
I did manage to get around it by downloading files not from Ru app, but from Flood, where you can select the target folder for each dl.

However, I still have an issue with embly streaming player, which reads the folder structure incorrectly and places files in random folders (very bothering with TV series with many episodes), when they're in their correct place in the file manager, and doing a search doesn't help since the files take the name of the folder embly places them in...

But only one ticket can be opened at a time, so that will wait...

**Comment by ramiresviana** [comment]
> I still experience the issue, when is the next release ?

This issue was fixed on 2.16.0, check your FileBrowser version.

**Comment by AshDevFr** [comment]
I am using the version `2.17.2`

**Comment by ramiresviana** [comment]
We need further details to reproduce the issue, please provide server environment details, configuration and logs.
