### ISSUE TITLE
HTTP 500 Error: Moving directory from one location to another

### ISSUE THREAD

**Issue by rtalaricw** [filebrowser/filebrowser#1936]
**Description**
Trying to move an empty dir from one location to another dir in another location

**Expected behaviour**
Dir to move to the other location

**What is happening instead?**
Getting 500 Errors

**How to reproduce?**

- Please create a directory A in the home folder. 
- Please create another directory B in the home folder.
- Try copying A into B

**Comment by sacwooky** [comment]
I'm also having this issue, same error if it's moving a folder or a file

**Comment by o1egl** [comment]
Can't reproduce it on the latest version. Please share your server logs

**Comment by elesiuta** [comment]
It only happens for me when moving a folder between different volumes
In my compose file I have these volumes
```
- ./srv:/srv
- /mnt/datadr0:/srv/datadr0
- /mnt/datadr1:/srv/datadr1
```
And in my logs I get the following (along with the 500 error) when moving `test` to a location on datadr1.
```
2022/05/16 02:43:20 /datadr0/tmp/test/: 500 10.1.1.2 read /srv/datadr0/tmp/test: is a directory
```
Selecting all the files within the folder and moving them to a folder on the other volume works just fine.

**Comment by tyrone2015** [comment]
Any other fixes now？

**Comment by cybrdyne** [comment]
Exact same issue for me. Cannot move a folder into another disk. :(

**Comment by cuicuifeng** [comment]
same issue for me. 403 Forbidden when moving a folder between different volumes

**Comment by picard12** [comment]
Same issue, but i can copy files/folders between different volumes, but i can copy and rename.

logs: `
`2022/09/10 05:32:34 /sda/FANTASCIENZA2/Pacific Rim -/: 500 192.168.1.17 read /srv/sda/FANTASCIENZA2/Pacific Rim -: is a directory

2022/09/10 05:51:26 /sda/FANTASCIENZA2/Pacific Rim -/: 500 192.168.1.17 read /srv/sda/FANTASCIENZA2/Pacific Rim -: is a directory`
`
My system; HA2209.1, filebrowser 2.22.4

filebrowser config

`version: "3"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
      ports:
      - 8407:80
    volumes:
        - /srv/dev-disk-by-uuid-6e900f49-d433-4ad8-ad6c-b58d124a6a17/:/srv/sda/
        - /srv/dev-disk-by-uuid-3960beb3-c85f-46e1-a512-49f9d3f58f0e/:/srv/sdb/
        - /srv/dev-disk-by-uuid-750aa4de-130e-4560-8eff-ab8665be747e:/srv/sdc/
        - /srv/dev-disk-by-uuid-18f59234-8957-4c26-b1b8-ef9ddf5cf2e1:/srv/sdd/
        - /opt/filebrowser/filebrowser.db:/config/filebrowser/database.db
        - /opt/filebrowser/filebrowser.json:/config/filebrowser/filebrowser.json
    environment:
      - FB_BASEURL=/filebrowser
      - PUID=1000
      - PGID=100
    restart: always
`

**Comment by picard12** [comment]
I noticed another aspect of the problem. If I have to move a folder with files inside, it gives error 500, but if I only move the files, no problem. So it seems that the 500 error is due to a folder management.

**Comment by picard12** [comment]
I can confirm the issue. It's  relate to only folder, not to the files inside. If I move only the files it's work right, but if try to move the folder, 500 error appear. Anyone have  the solution?

**Comment by YunofHD** [comment]
I have the same Issue 
Pls see the log as below 
`s6-rc: info: service 99-ci-service-check successfully started`

`2022/11/07 06:25:19 Using config file: /config/settings.json`

`2022/11/07 06:25:19 Listening on [::]:80`

`2022/11/07 06:27:39 /Download/Thor.Love.and.Thunder.2022.2160p.WEB-DL.x265.10bit.SDR.DDP5.1.Atmos-NOGRP/: 500 192.168.0.201 read /srv/Download/Thor.Love.and.Thunder.2022.2160p.WEB-DL.x265.10bit.SDR.DDP5.1.Atmos-NOGRP: is a directory`

`2022/11/07 06:30:58 /Download/Thor.Love.and.Thunder.2022.2160p.WEB-DL.x265.10bit.SDR.DDP5.1.Atmos-NOGRP/Thor.Love.and.Thunder.2022.2160p.WEB-DL.x265.10bit.SDR.DDP5.1.Atmos-NOGRP.mkv: 403 192.168.0.201 chmod /srv/Movie/Wait-to-Handle/Thor.Love.and.Thunder.2022.2160p.WEB-DL.x265.10bit.SDR.DDP5.1.Atmos-NOGRP.mkv: operation not permitted`

`2022/11/07 06:30:58 /Download/Thor.Love.and.Thunder.2022.2160p.WEB-DL.x265.10bit.SDR.DDP5.1.Atmos-NOGRP/Thor.Love.and.Thunder.2022.2160p.WEB-DL.x265.10bit.SDR.DDP5.1.Atmos-NOGRP.mkv: 403 192.168.0.201 chmod /srv/Movie/Wait-to-Handle/Thor.Love.and.Thunder.2022.2160p.WEB-DL.x265.10bit.SDR.DDP5.1.Atmos-NOGRP.mkv: operation not permitted`

**Comment by picard12** [comment]
I tested another file manager like cloudcommanders, in parallel with filebrowsers with the same files. The result is that filebowsers fails when trying to move directories.

**Comment by antoinedelia** [comment]
I'm also having the exact same problem. Is this something that is planned to be worked on or not at all?

**Comment by azcn2503** [comment]
I am experiencing the same issue. I just installed `filebrowser` via Docker yesterday (tag: `latest`, updated 3 months ago).

This is the associated log message from `docker logs filebrowser -f`:

```
2023/02/17 07:46:21 /Downloads/Test Folder/: 500 192.168.86.58 read /srv/Downloads/Test Folder: is a directory
```

**Comment by slhmy** [comment]
I will raise a PR to fix this ISSUE

**Comment by cybrdyne** [comment]
Did anyone find something for resolution?

**Comment by azcn2503** [comment]
This is still an issue. A workaround is to copy from `a` to `b`, then delete `a`.

**Comment by slhmy** [comment]
> I will raise a PR to fix this ISSUE

I need someone to review this PR #2349 , then I think this issue should be fixed after merge.

**Comment by azcn2503** [comment]
This is still an issue. Additionally, the linked PR has been auto closed due to the overly aggressive github actions. Issues rarely resolve themselves without manual intervention, so perhaps the github actions need to be revised to prevent comments like these.

**Comment by markwoodward86** [comment]
reporting same issue. Fresh install just now. The copy file workaround seemed to work in the browser uI but changes were not reflected in any other environment/application

**Comment by ericlamus** [comment]
Reporting same issue. Fresh install as well.

**Comment by alrapine** [comment]
What the password on db, to manually changing filenames?
