### ISSUE TITLE
Auto create user home dir while adding new user has no effect

### ISSUE THREAD

**Issue by princemaple** [filebrowser/filebrowser#1954]
**Description**
There is an option in global settings:
Auto create user home dir while adding new user 

~Turning it on has no effect~

**Expected behaviour**
When adding new user with root like `/var/www/roots/123`, I'd like to see it being created automatically, especially when `/var/www/roots` already exists.

**What is happening instead?**
It has no effect

**Additional context**
N/A

**How to reproduce?**
Turn on this option, create a new user with a easy to locate root, that does not exist yet.

Expect to find it created after creating the user, but no it is not created.

**EDIT**: the above is inaccurate. see https://github.com/filebrowser/filebrowser/issues/1954#issuecomment-1132273092 for more precise bug description.

**Comment by ramiresviana** [comment]
Filebrowser will create a directory for the user when the Auto Create option is enabled. It follows these steps when creating a new user:

1. Check if the user scope is empty.
2. Create a new directory called users on the application root.
3. Create a new directory with the username on the users directory.
4. Set the user scope to the new directory.

All directories are created recursively. Server console will have information when a new home dir is created, if there's something wrong you should get errors.

**Comment by mckaygerhard** [comment]
This must be marked as solved.. cos was not a bug and later be converted ina discussion to move to the discussion group.. you always are there @ramiresviana  why @o1egl  dont give you right access to manage the project?

**Comment by princemaple** [comment]
Thanks @ramiresviana . This actually works. I misunderstood how this is supposed to work.

My filebrowser is started with `-r /var/www`.

I've always created new users with scope `/var/www/roots/USER_ID`. I've realized that `/var/www` is not needed here.

When auto create home dir is turned on, with `-r /var/www`, and new user scope `/var/www/roots/123`, the home dir is actually created as `/var/www/var/www/roots/123`. This might be the actual "bug", if you'd like to call it a bug.

The thing is, the scope has always worked - meaning it is treated as a full path. However, the way the home dir is created tells me that the auto creation takes the scope and does a concatenation. So, there is an implementation mismatch - taking the scope as full path or sub path.

**Comment by ramiresviana** [comment]
When creating a home dir, the path is always appended to the application root, like this: 
```
app-root / user-settings-defaut-scope / "users" / username
```
This is really confusing, the scope can be a absolute path but not for created home dirs. I think that this could be considered a bug.

**Comment by mckaygerhard** [comment]
this was addressed at my taks over documentation but as you noted @ramiresviana  .. the issue just was closed.. i checked at the commits that there's nothig related as "solved" by you or @o1egl 

my only complaint is precisely the very minimalist documentation and the attitude of "that is assumed"

the more detailed the better this way these problems of misinterpretation are avoided

thanks for filebrowser.. is a great program..

**Comment by princemaple** [comment]
Hmm, 2.22 didn't really solve it. It simply killed the possibilities to specify where to create the user specific home directory. It's kinda disappointing 😢

**Comment by princemaple** [comment]
Oh it's more problematic than I thought. It's broken for all users that have an absolute path home directory...

Say filebrowser root is at `/a/b`, I used to have users home directory specified as `/a/b/c`. Now it doesn't work, only `c` works. I had to revert back to 2.21.

**Comment by mckaygerhard** [comment]
> Say filebrowser root is at `/a/b`, I used to have users home directory specified as `/a/b/c`. Now it doesn't work, only `c` works. I had to revert back to 2.21.

well @princemaple  unless you are a windoser, this is the xpected results, i will explain why:

usage of absolute paths cannot be allowed from web frontends.. only must be for system admin of the server and not by the manager of the web applications.. as must be..

so i guess as the commit said in https://github.com/filebrowser/filebrowser/commit/02730bb9bfa3bfbfa251bb4736fc4c08d33609ab the correct behaviour is using with path home base.. this means:

before you have `/a/home` and used to have users home directory specified as `/a/home/c` with user `bob` was `/a/home/c/bob` was wrong, cos allow absolute paths and can be a security flaw

now you have `/a/home` and used to have users home directory specified as `c` with user `bob` was `/a/home/c/bob` and if that is now as is @o1egl  the fix are wrong.. (i not tested..  just check the sources)

**Comment by princemaple** [comment]
I've updated all users to have a relative home path, so I'm no longer bothered by this problem.

However, it's not a security issue to specify them as absolute path. 1. You can check the prefix, 2. Only an admin can set it.

**Comment by o1egl** [comment]
The issue is fixed in v2.22.0. Any root and relative paths are now correctly merged with the global filebrowser root.
