### ISSUE TITLE
v2.24.2 unable to upload image

### ISSUE THREAD

**Issue by kimxuantv** [filebrowser/filebrowser#2650]
Hello
I using v2.24.2 unable to upload image files please see the photo in below
http://171.224.104.204/share/7HSkEt1X
Thanks.

**Comment by StevenWittmann** [comment]
Same here 
![image](https://github.com/filebrowser/filebrowser/assets/124083922/521855c7-99b6-43c2-8157-db36f5c86218)

**Comment by kimxuantv** [comment]
> Same here ![image](https://user-images.githubusercontent.com/124083922/260636519-521855c7-99b6-43c2-8157-db36f5c86218.png)

Ahaha we have a friends. Nobody help this issues. 
Why unable upload image with latest version?

**Comment by jniggemann** [comment]
Doesn't happen to me, tried with PNG, JPG and even GIF. HTTP 405 error message confirms that the requested page does exist (and the URL was input correctly), but an unacceptable HTTP method was used to make the initial request.

Can you look into the logfile to see if there's something that may help?

**Comment by NextrixVFX** [comment]
a quick fix i figured out is to rename the image to use the .txt extension and then upload it, when done uploading just rename the extension back to a png or whatever. Not the nicest solution but works...

**Comment by kimxuantv** [comment]
> 



> Doesn't happen to me, tried with PNG, JPG and even GIF. HTTP 405 error message confirms that the requested page does exist (and the URL was input correctly), but an unacceptable HTTP method was used to make the initial request.
> 
> Can you look into the logfile to see if there's something that may help?

Hello, this is log
2023/08/16 00:24:35 /thumb/hung.ly/hoadon phoi cho Husky Cotton 2018.JPG: 500 192.168.1.5 image: unknown format: unsupported image format
What version are you using?

**Comment by NextrixVFX** [comment]
I did some looking and the issue somewhat has something to do with cloudflare (files.nextrix.xyz) But when I connect to it locally (10.0.0.174:80) it fully works!

Until a new fix comes out the best solution I've found is to just connect to it locally.

Though, renaming the file to have the extension txt and uploading it and naming it back to png works just fine too but is more time consuming.
(it works with any file not just png's btw.)

**Comment by jniggemann** [comment]
> What version are you using?
I'm using 2.24.2 and accessing it locally.

**Comment by kimxuantv** [comment]
> I'm using 2.24.2
I'm using 2.24.2 too, also i'm installed on docker.

**Comment by kimxuantv** [comment]
> I did some looking and the issue somewhat has something to do with cloudflare (files.nextrix.xyz) But when I connect to it locally (10.0.0.174:80) it fully works!
> 
> Until a new fix comes out the best solution I've found is to just connect to it locally.
> 
> Though, renaming the file to have the extension txt and uploading it and naming it back to png works just fine too but is more time consuming. (it works with any file not just png's btw.)

Hello, thank for you response, i can upload jpg png work fine with v2.23.0 so when i upgrade to v2.24.2 just upload tif and bmp.

**Comment by NextrixVFX** [comment]
> > I did some looking and the issue somewhat has something to do with cloudflare (files.nextrix.xyz) But when I connect to it locally (10.0.0.174:80) it fully works!
> > Until a new fix comes out the best solution I've found is to just connect to it locally.
> > Though, renaming the file to have the extension txt and uploading it and naming it back to png works just fine too but is more time consuming. (it works with any file not just png's btw.)
> 
> Hello, thank for you response, i can upload jpg png work fine with v2.23.0 so when i upgrade to v2.24.2 just upload tif and bmp.

I tried to downgrade to v2.23.0 yesterday but when I would try to upload literally anything I would get a error 403 or something which has been fixed in the newer versions...

I run my filebrowser on portainer (docker webgui) btw.

The issue I'm having however is that I can't upload any files besides text formatted files like .py or .html or .txt
When I try to upload anything else (.jar, .zip, .rar, etc...) it has the same 405 error which makes it even more inconvenient.

**Comment by NextrixVFX** [comment]
@kimxuantv Found a fix at here https://github.com/filebrowser/filebrowser/issues/2588#issuecomment-1664335304

Works perfectly now!

**Comment by kimxuantv** [comment]
> @kimxuantv Found a fix at here [#2588 (comment)](https://github.com/filebrowser/filebrowser/issues/2588#issuecomment-1664335304)
> 
> Works perfectly now!

Hello, I have do that still do not work hahaha
I have add my domain to CF and DNS to june.ns.cloudflare.com finley.ns.cloudflare.com
same issues 
Thanks.

**Comment by masterwishx** [comment]
Also have this problem when uplaoding files

**Comment by masterwishx** [comment]
Fixed by https://github.com/filebrowser/filebrowser/issues/2588#issuecomment-1664335304

**Comment by masterwishx** [comment]
but not for pictures files

**Comment by kimxuantv** [comment]
> Fixed by [#2588 (comment)](https://github.com/filebrowser/filebrowser/issues/2588#issuecomment-1664335304)

Hello, i had do that so do not work, what is the problem with my issues?
Thanks.

**Comment by DcryptedCA** [comment]
Same issue, this is related to Cloudflare for me. Works on IP directly NOT when going through Cloudflare.

**Comment by kimxuantv** [comment]
> but not for pictures files

me too, please help urgent

**Comment by Cretezy** [comment]
I was having the same issue using nginx (with Nginx Proxy Manager) locally, without Cloudflare.

I fixed it by disabled the "Cache Assets" option.

**Comment by kimxuantv** [comment]
> I was having the same issue using nginx (with Nginx Proxy Manager) locally, without Cloudflare.
> 
> I fixed it by disabled the "Cache Assets" option.

Omg, thank you i have upload picture work fine.
Thank you so much.

**Comment by masterwishx** [comment]
> I was having the same issue using nginx (with Nginx Proxy Manager) locally, without Cloudflare.
> 
> I fixed it by disabled the "Cache Assets" option.

Thanks, now also pictures upload aslo work for me

**Comment by masterwishx** [comment]
For upload fix, I used cloudflare fix (files upload) + NPM fix (images upload)

**Comment by revolvedai** [comment]
@masterwishx What was NPM fix? I can't find that.

**Comment by masterwishx** [comment]
> What was NPM fix? I can't find that.

https://github.com/filebrowser/filebrowser/issues/2650#issuecomment-1695757908

**Comment by o1egl** [comment]
Check https://github.com/filebrowser/filebrowser/issues/2593#issuecomment-1720153087
