### ISSUE TITLE
No change when modifying custom branding/CSS OMV

### ISSUE THREAD

**Issue by 2lag** [filebrowser/filebrowser#2752]
**Description**
The issue, as the title hints at, is with custom branding with the OpenMediaVault ( OMV ) filebrowser plugin. No matter what path, whether full, or local to the extension, nor which files are contained in the directory, will change the appearance or logos for the login or browsing pages. I have read all the other issues, open and closed, referring to custom branding, and I have come up with absolutely nothing.

**Expected behaviour**
I expected the logos to update and the login screen to change styling.

**What is happening instead?**
Absolutely nothing.

**Additional context**
Directory and contained files :
![image](https://github.com/filebrowser/filebrowser/assets/96544487/a969e4d7-c884-493a-944b-302d2bd6b4fb)<br>
File Browser settings :
![image](https://github.com/filebrowser/filebrowser/assets/96544487/feb39044-d02b-4121-9eb0-5f683dad974e)<br>

**How to reproduce?**
Place files in respective directories, change settings, wait 24h and/or disable and clear caching, _nothing._

**Files**
Copied custom.css to test from #2379 and disabled cache as suggested, still no change after waiting 48 hours testing each form of path.

**Comment by 2lag** [comment]
I've changed the location and path to `/var/www/openmediavault/branding` for the past few days and that didn't make any change, so I just modified it with the absolute path of the branding folder within the filebrowser folder containing the filebrowser.db file, as seen here:
Mine -
![image](https://github.com/filebrowser/filebrowser/assets/96544487/1759d804-88bf-4d63-9454-84f956bf55bd)
Documentation's -
![image](https://github.com/filebrowser/filebrowser/assets/96544487/ea559fce-8c14-4091-9a32-101dae7a4349)

I will update this issue if it happens to fix the problem, but I have already tried it so my hopes aren't too high.

**Comment by 2lag** [comment]
Has nobody gotten this to work? I feel like the fix should be super simple, documentation specified absolute path for the CLI input, but clearly it isn't working with my current directory. Could it be a permissions issue maybe?
![604616224d0fd60050e16268fcd7b381](https://github.com/filebrowser/filebrowser/assets/96544487/160b5c59-6cb9-42e1-8d4c-9bcf651661df)

**Comment by swatoner** [comment]
> with the OpenMediaVault ( OMV ) filebrowser plugin. No matter what path, whether full, or local to the extension, nor which files are contained in the directory, will change the appearance or logos for the login or browsing pages. I have read all the other issues, open and closed, referring to custom branding, and I have come up with absolutely nothing.

I am not sure if this can help you since i dont use OMV but I have implemented using docker.
In docker I have mounted a physical path as volume "/branding" and then configured the filebrowser app to check the branding path "/branding"
I assume that OMV doesnt expose directly the physical path of the folder and makes static links same as Docker does. Even consider uses docker engine to host applications.
I assume that "/var/www/openmediavault/branding" isnt a folder that the filebrowser can reach out.

![image](https://github.com/filebrowser/filebrowser/assets/33767181/583fdb51-0e3b-4600-bb39-d93697e7f571)
![image](https://github.com/filebrowser/filebrowser/assets/33767181/39ed9569-fa12-4433-af70-f079db94fa4b)

**Comment by 2lag** [comment]
I have the images contained within the filebrowser directory shown above in my previous comments, so it should have access/permission. I just changed it back to `/branding` though so we'll see if it updates.

**Comment by 2lag** [comment]
Still no change, and I've had file caching disable this whole time. Directory is still the same as seen here :
![image](https://github.com/filebrowser/filebrowser/assets/96544487/08ac052f-f828-42b4-ada8-af0eaede8297)
Only thing I can think is that the folder needs to go in a different directory maybe?
Could you by chance show me the contents of your /Docker/filebrowser/ directory @swatoner ? Or if not, just confirm that you have the same files in the /filebrowser/ folder so I can make sure I have everything in the right path?
Thank you 😃

**Comment by JackloveJam** [comment]
好的，各位。我也是使用者。
我复现了不显示自定义图标的问题。
一开始我也是按照官方教程，并且将logo文件以及目录创建在filebrowser目录下。这是不行的，不知道为什么会读取不到。
解决办法：将这些图片换到其他目录
以下是我的挂载目录映射关系：
D:\docker-compose\file-browser\root /srv
D:\docker-compose\file-browser\filebrowser.db /database.db
D:\docker-compose\file-browser\filebrowser.json /.filebrowser.json
静态资源挂载路径 
D:\docker-compose\image\branding /branding
$ pwd
/d/docker-compose/image/branding/img
$ ls
icons/  logo.svg
最后就是在全局设置中将路径设置为
/branding
清除缓存即可看到萌萌哒的坤坤图标了。
![image](https://github.com/filebrowser/filebrowser/assets/135937895/5eb61a85-9ed9-4767-a0bf-1b7388d4d9eb)
![image](https://github.com/filebrowser/filebrowser/assets/135937895/f2ab6ea7-b78f-48ac-9d24-2b67e98dac26)

**Comment by 2lag** [comment]
> 好的，各位。我也是使用者。 我复现了不显示自定义图标的问题。 一开始我也是按照官方教程，并且将logo文件以及目录创建在filebrowser目录下。这是不行的，不知道为什么会读取不到。 解决办法：将这些图片换到其他目录 以下是我的挂载目录映射关系： D:\docker-compose\file-browser\root /srv D:\docker-compose\file-browser\filebrowser.db /database.db D:\docker-compose\file-browser\filebrowser.json /.filebrowser.json 静态资源挂载路径 D:\docker-compose\image\branding /branding $ pwd /d/docker-compose/image/branding/img $ ls icons/ logo.svg 最后就是在全局设置中将路径设置为 /branding 清除缓存即可看到萌萌哒的坤坤图标了...

您好，我尝试按照您的指示进行操作，但似乎仍然无法正常工作。我使用的是 OpenMediaVault，而不是 Docker，所以我确信它们不会进行 1:1 的复制。我尝试创建一个共享文件夹，并将目录移动到与 FileBrowser 一起使用的共享文件夹内，但仍然没有成功。如果您有任何建议或需要专门查看任何内容以提供帮助，我不介意尽早提供。我只是厌倦了这个问题哈哈。

**Comment by 2lag** [comment]
I have found [this](https://forum.openmediavault.org/index.php?thread/45650-custom-branding-in-filebrowser-plugin/), but it's not really helping as I'm unsure what my root directory is for OMV. If there is an easy way to find it, please let me know!

Edit: I have found my root folder, and have also added another shared folder with the relative path of `branding/`, and the absolute path of `/srv/dev-disk-by-uuid-XXXX/branding` ( dev-disk-etc... due to RAID as far as I know ), right next to my other shared folder that is the one actually hosted through the FileBrowser plugin on OpenMediaVault ( and fully functional ).

My "Branding directory path" within FileBrowser -> Settings -> Global Settings is also set to `/srv/dev-disk-by-uuid-XXXX/branding` for now. I tried CTRL+Shift+R, which should ignore cache and reset the page, but still no change. I have done the same with also just `/branding`, and same thing there. @swatoner I believe this is the closest I've come to a similar solution to what you have. Any further suggestions would be greatly appreciated.

Also, these are the only "filebrowser" folders I have.
![image](https://github.com/filebrowser/filebrowser/assets/96544487/e38c0d92-96f7-433c-8266-2005745b2760)

**Comment by JackloveJam** [comment]
> > 好的，各位。我也是使用者。 我复现了不显示自定义图标的问题。 一开始我也是按照官方教程，并且将logo文件以及目录创建在filebrowser目录下。这是不行的，不知道为什么会读取不到。 解决办法：将这些图片换到其他目录 以下是我的挂载目录映射关系： D:\docker-compose\file-browser\root /srv D:\docker-compose\file-browser\filebrowser.db /database.db D:\docker-compose\file-browser\filebrowser.json /.filebrowser.json 静态资源挂载路径 D:\docker-compose\image\branding /branding $ pwd /d/docker-compose/image/branding/img $ ls icons/ logo.svg 最后就是在全局设置中将路径设置为 /branding 清除缓存即可看到萌萌哒的坤坤图标了...
> 
> 您好，我尝试按照您的指示进行操作，但似乎仍然无法正常工作。我使用的是 OpenMediaVault，而不是 Docker，所以我确信它们不会进行 1:1 的复制。我尝试创建一个共享文件夹，并将目录移动到与 FileBrowser 一起使用的共享文件夹内，但仍然没有成功。如果您有任何建议或需要专门查看任何内容以提供帮助，我不介意尽早提供。我只是厌倦了这个问题哈哈。

好的。我看到了你的回复。
如果是这样尝试也没能拯救你，那么我建议你可以尝试在你的OMV中使用docker/docker-compose部署。（不知道这样对你是不是增加了难度）
![479F0AD0](https://github.com/filebrowser/filebrowser/assets/135937895/029bb4d1-6150-4ea6-ac87-ea53d2aef74b)

**Comment by ngroulx** [comment]
You ever manage to get the branding working? I've been beating my head against the wall with this same issue.

**Comment by 2lag** [comment]
Nope, still beating my head against a wall over here as well. If you're able to find a solution that doesn't use Docker, please let me know... @ngroulx 

Edit: Sorry for late response, have been busy with other projects haha

**Comment by niubility000** [comment]
The following is nothing about docker. I don't use docker, but I hope it may help. 

It's a small bug.
The root dir (.) in the setting-global settings-Branding directory path is the cmd windows dir, not the e: (when you run .\filebrowser.exe -d filebrowser.db config set --root e:/ )
For example, when you run: C:\Users\www> c:\go\src\filebrowser\filebrowser.exe，the root dir means c:\Users\www\ . So put your custom.css in c:\users\www folder.
After you change the branding directory path, you need restart the filebrowser.exe and the browser to make it work. 

And when you run the command C:\Users\www> c:\go\src\filebrowser\filebrowser.exe, It will try to use the filebrowser.db in c:\Users\www. If there is no filebrowser.db in c:\Users\www\, it will initial one in this dir. not in the folder c:\go\src\filebrowser. So when you use 
.\filebrowser.exe config set --branding.files "d:\filebrowser" 
to set the branding dir path, you need to make sure which filebrowser.db you are writting in, and use the same filebrowser.db when you run filebrowser.exe.


So when you use command line, Always use" -d ", for exmple:
C:\Users\www> c:\go\src\filebrowser\filebrowser.exe -d d:\filebrowser\filebrowser.db config set --branding.files "d:\filebrowser"  
when you set the branding dir path. and 

C:\Users\www> c:\go\src\filebrowser\filebrowser.exe -d d:\filebrowser\filebrowser.db --disable-preview-resize --cache-dir d:\filebrowser\cache  
when you start the filebrowser service.

BTW, do you guys have any decent custom.css to share?

**Comment by ngroulx** [comment]
@niubility000 thank you for the detailed reply. Unfortunately I don't think that applies in my situation?
I don't know about @2lag but we are running this as a service inside of a Linux environment.

**Comment by 2lag** [comment]
I am running filebrowser through OpenMediaVault, so it's a built in plugin. I'll take a crack at your fix and report back.

**Comment by 2lag** [comment]
Some notes about what I have found, in the search for a fix, I have found yet again : `/var/lib/filebrowser/`
This contains  the following :
 - Caddyfile
 - database.db
 - filebrowser.json

If you open `filebrowser.json`, there is a line containing `root: "/______"`, in my case `root: "/srv"`

I've attempted to put the branding directory in Filebrower's root folder `/srv/branding/custom.css`, and then in global settings, for "Branding directory path", the following:
![image](https://github.com/filebrowser/filebrowser/assets/96544487/dd1fb9a9-aea9-4ae6-be8e-f43f1f3d341c)

Hopefully this works, will make an update if it does.

**Comment by 2lag** [comment]
Update: It does not... I really thought this would be **the one**.

**Comment by tekunikaru** [comment]
I'm having this exact same issue on a Windows Server 2022. I've tried the resources provided here, no luck.
Using File Browser 2.27.0

**Comment by niubility000** [comment]
> I'm having this exact same issue on a Windows Server 2022. I've tried the resources provided here, no luck. Using File Browser 2.27.0

Try this:
Use the **absolute path** in Branding directory path, put the custum.css in that path.
![3](https://github.com/filebrowser/filebrowser/assets/76441520/93d73d37-c8c4-475d-b837-1c8332c5df25)

Then **restart your filebrowser service** and **your browser**.

**Comment by 2lag** [comment]
I currently have it to the absolute path, `/srv/branding`, still no luck

**Comment by niubility000** [comment]
> I currently have it to the absolute path, `/srv/branding`, still no luck

Have you restarted the filebrowser? Or maybe the abs path is wrong.  maybe `./srv/branding`
I think after #3028 is merged, you can get your abs path directly.

**Comment by 2lag** [comment]
Yes, I restarted the entire machine every time and disabled caching so it should've updated. I tried `./srv/branding` as well, no luck.
The root dir for filebrowser is `/srv`, so the absolute path for the branding folder would be `/srv/branding`, but still no dice.

**Comment by tekunikaru** [comment]
> Try this: Use the **absolute path** in Branding directory path, put the custum.css in that path.
> 
> Then **restart your filebrowser service** and **your browser**.

I did this and other stuff, with multiple client devices, sandboxes and not only keeping Cloudflare in developer mode but always purging my cache every restart. I noticed that I can only access custom.css and the favicon.ico, but not logo.svg and other icons.

I'm unsure why this is happening as I inspected the source looking for anything that might be causing this (I'm not an experienced GO or Vue developer, tho). But I didn't stress too much about it since I was already going to modify the source to add features. So I ended up changing the icons directly.

To help out, I'm going to try to reproduce the problem again on a fresh Windows Server sandbox. I'll post results here later.

**Comment by 2lag** [comment]
I just went through and replaced every instance of logo.svg... And still no change. There has to be something I'm missing here.

**Comment by niubility000** [comment]
> I just went through and replaced every instance of logo.svg... And still no change. There has to be something I'm missing here.

Maybe this is a bug. It should not be this hard. I tried in a new window pc, the custom.css doesn't work there. and I initialed a new database, it works. it's weird. We may analysis the source code to figure it out.

**Comment by niubility000** [comment]
> I just went through and replaced every instance of logo.svg... And still no change. There has to be something I'm missing here.

I got it. Maybe it's a kind of bug. 
You need to initial **a new database file** filebrowser.db.  And **before you run filebrowser.exe firstly**, you need to run: config set --branding.files "d:\filebrowser",  and put your custom.css in d:\filebrowser, and logo.svg in d:\filebrowser\img, then run the filebrowser.exe using the new database file. Then it works.
After that, you can't modify the logo.svg, custom.css or the branding.file path, It will not work any more. **Because the logo.svg and custom.css is already written into filebrowser.db. It will not judge if the logo.svg or custom.css is modified.** It only judge if there is a branding.file path in the setting and if there is a custom.css, logo.svg in that folder. If yes, it will use the data directly from filebrowser.db. It will not update the filebrowser.db from the new custom.css and logo.svg.

 For example: 
put the custom.css in d:\filebrowserand logo.svg in d:\filebrowser\img, then
(in windows cmd)
ctrl+c to shut down the filebrowser.exe, 
cd c:\test     Make sure there is no filebrowser.db in this c:\test folder. 
c:\go\src\filebrowser\filebrowser.exe -d filebrowser.db config init
c:\go\src\filebrowser\filebrowser.exe -d filebrowser.db users add aaa 123456 --perm.admin
c:\go\src\filebrowser\filebrowser.exe -d filebrowser.db config set --address 0.0.0.0
c:\go\src\filebrowser\filebrowser.exe -d filebrowser.db config set --root d:/
c:\go\src\filebrowser\filebrowser.exe -d filebrowser.db  config set --branding.files "d:\filebrowser"
c:\go\src\filebrowser\filebrowser.exe -d filebrowser.db

Then visit at 127.0.0.1:8080 with aaa:123456, you will see the new logo and custum style. After that, you can't change it unless you initial a new database.

I think the bug is from func getStaticHandlers() in static.go.

**Comment by 2lag** [comment]
I'm using the filebrowser plugin through OpenMediaVault, so it's running Debian if I remember correctly. It may be a specific bug to using it this way, that's really all I can assume at this point. I don't have a `filebrowser.db`, the closest thing is `database.db` that's in my `/var/lib/filebrowser/` directory, along with that `filebrowser.json` I mentioned earlier.

Edit: `database.db` is the same as `filebrowser.db` according to `filebrowser.json`, got the PID and it does seem to be running in a Docker pod, but anytime I tried to do anything to it: restarting, accessing program info, etc., it would stop working altogether.

Just now seeing your screenshots loaded and I'm not versed in Go but it looks like it could be correct. Curious if this is the end-all-be-all solution...

**Comment by niubility000** [comment]
> I'm using the filebrowser plugin through OpenMediaVault, so it's running Debian if I remember correctly. It may be a specific bug to using it this way, that's really all I can assume at this point. I don't have a `filebrowser.db`, the closest thing is `database.db` that's in my `/var/lib/filebrowser/` directory, along with that `filebrowser.json` I mentioned earlier.

I don't know how to help you out since I don't have the env.
Maybe just shut down the filebrowser, and rename the database.db to any other name, 
Put a custom.css in a folder. This will change the folder's color to yellow. 
#listing .item[data-dir=true] div i {
    color: #ffc84b;
}
and run the command above. It will initial a new database.db, and change the branding file path. 

and restart your filebrowser . Then, you can see the new style.

**Comment by 2lag** [comment]
I think it should work as-is though.

My filebrowser.json ( as-is from install ):
```json
{
  "port": 8080,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv"
}
```
Though I will note here, it doesn't quite make sense that one is local and the other is absolute as far as the `database` and `root` paths go...

ls of directory ( ignore the `branding` directory here, I've had to place it in several places ):
```
root@kuso:/var/lib/filebrowser# ls
branding  Caddyfile  database.db  filebrowser.json
```

**Comment by 2lag** [comment]
Man.

**Comment by Uerum18** [comment]
@2lag Just in case, did you try to add a trailing slash to your branding path ("/srv/branding/")?
It fixes the issue in my case, but I'm still figuring out how to set this path as default.

**Comment by bharath063** [comment]
> > with the OpenMediaVault ( OMV ) filebrowser plugin. No matter what path, whether full, or local to the extension, nor which files are contained in the directory, will change the appearance or logos for the login or browsing pages. I have read all the other issues, open and closed, referring to custom branding, and I have come up with absolutely nothing.
> 
> I am not sure if this can help you since i dont use OMV but I have implemented using docker. In docker I have mounted a physical path as volume "/branding" and then configured the filebrowser app to check the branding path "/branding" I assume that OMV doesnt expose directly the physical path of the folder and makes static links same as Docker does. Even consider uses docker engine to host applications. I assume that "/var/www/openmediavault/branding" isnt a folder that the filebrowser can reach out.
> 
> ![image](https://private-user-images.githubusercontent.com/33767181/283117692-583fdb51-0e3b-4600-bb39-d93697e7f571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDYwMjIsIm5iZiI6MTcyMDYwNTcyMiwicGF0aCI6Ii8zMzc2NzE4MS8yODMxMTc2OTItNTgzZmRiNTEtMGUzYi00NjAwLWJiMzktZDkzNjk3ZTdmNTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEwMDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NGI2ZmQ5ZDZkNzVlZjRiNTJkMjk1YTdmZTJmZGJiMjAwYmUzMTU3MGViMDIzMDBmZTlkM2QxZTgyNDdkZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YCIawsK7rxZr3_CHk_6UmQmsR50s15DFsizGjMUUUf8) ![image](https://private-user-images.githubusercontent.com/33767181/283117840-39ed9569-fa12-4433-af70-f079db94fa4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDYwMjIsIm5iZiI6MTcyMDYwNTcyMiwicGF0aCI6Ii8zMzc2NzE4MS8yODMxMTc4NDAtMzllZDk1NjktZmExMi00NDMzLWFmNzAtZjA3OWRiOTRmYTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEwMDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZjZkOTg5NmIwN2Y5ZTczZjIyNTQ0MmM3NzU3MzIxZjRkMDY2NzQwNzllNmY5YWY5ZTA2NDY3ZjFiZjA1NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O3xGZFFdwXyZOP4RBmolYeaMurZYheDDR6Mm1HxKIjk)

Thanks. This worked for me in CasaOS.
I just had to mount a volume to /branding that contains the img directory
Then in the file browser web app, under setting, I changed the directory to /branding and it worked

**Comment by JackKay404** [comment]
For me the problem was my image file was a png and not a proper svg. Also the name of the file should be "logo.svg". 
For the favicon in the browser tab bar, you need to have 32x32 and 16x16 size .png images in order to use the icon in the browser. The website in the docs only generates a 48x48 which presumably doesn't fit. This website worked for me: https://favicon.io/favicon-converter/

This was a massive pain which could have been made easy with about two lines of explanation in the documentation.
