### ISSUE TITLE
Filebrowser docker container in unhealthy status

### ISSUE THREAD

**Issue by pipsen** [filebrowser/filebrowser#3139]
**Description**
My FileBrowser Docker container works like a charm. But for several weeks already, the unhealthy flag is active but I don't neither see any error message in the docker logs, nor any misbehaviour.

**Expected behaviour**
Healthy docker container status flag

**What is happening instead?**
Unhealthy docker container status flag

**Additional context**
n/A

**How to reproduce?**
Directly after deployment and start

**Files**
![log](https://github.com/filebrowser/filebrowser/assets/15525250/956c11a8-6a93-438f-bfe2-991bdb3e945d)

**Comment by krovla** [comment]
See #3085 #2938

running this code will do the trick (container's named "filebrowser") 
`docker exec -it filebrowser sh -c "sed -i 's|ADDRESS=\\${FB_ADDRESS:-$(jq .address /.filebrowser.json)}|ADDRESS=\\${FB_ADDRESS:-$(jq -r .address /.filebrowser.json)}|g' healthcheck.sh"`

or in the terminal of your filebrowser container
`sed -i 's|ADDRESS=\${FB_ADDRESS:-$(jq .address /.filebrowser.json)}|ADDRESS=\${FB_ADDRESS:-$(jq -r .address /.filebrowser.json)}|g' healthcheck.sh`

**Comment by pipsen** [comment]
Thank you for the hint. That means this will fixed automatically with one of the next docker image updates right?

**Comment by Guiorgy** [comment]
@pipsen duplicate of #3085, and yes, the fix is awaiting to be merged and released

**Comment by Guiorgy** [comment]
FYI, the fix has been merged (#3130).

**Comment by blinkitogaming** [comment]
Hi there, I've updated the container to version 2.28.0 which seems to have this PR included and is supposed to fix this but I'm still getting the unhealthy status with the "bad hostname" output.

If I get into the container console and cat the file the -r flag is still not present.
![Screenshot 2024-04-26 121412](https://github.com/filebrowser/filebrowser/assets/87893192/5d582708-7b8f-467f-a1d0-f6a20c55dc17)

**Comment by Guiorgy** [comment]
@blinkitogaming m8, that release was published over a month ago, the PR (#3130) was submitted a week ago and merged 2 days ago. How did you come to the conclusion that the release has that PR? 😅

**Comment by chuckmister74** [comment]
Can confirm that version 2.29.0 has solved this issue for me.

**Comment by Guiorgy** [comment]
@pipsen Can you confirm that the new update solved the problem?

**Comment by pipsen** [comment]
Yes, I can confirm

**Comment by Guiorgy** [comment]
@pipsen Then the issue can be closed as completed.
