### ISSUE TITLE
mkv can't be played on filebrowser version 2.29.0, but ok on 2.28.0

### ISSUE THREAD

**Issue by Arthur2012** [filebrowser/filebrowser#3182]
**Description**
mkv can't be played on filebrowser version 2.29.0, but ok on 2.28.0

**Expected behaviour**
mkv should be played on filebrowser version 2.29.0, as same as ok on 2.28.0

**What is happening instead?**
mkv can't be played on filebrowser version 2.29.0

**Additional context**
error message: No compatible source was found for this media.

**How to reproduce?**
click any mkv file

**Files**
windows-amd64-filebrowser.zip version 2.29.0

**Comment by dhanushkt** [comment]
Yes, i can confirm this behavour on 2.29.0.
cant open .mkv files to play the media, error - No compatible source was found for this media.
tested on Firefox 125.0.3 and Google Chrome 124.0.6367.91

**Comment by kloon15** [comment]
I believe @gdy666 already fixed this issue and has been merged, so this should be working again in the next release.

**Comment by Arthur2012** [comment]
This issue was resolved and verified ok on version 2.30.0.

**Comment by harryqt** [comment]
`File Browser v2.31.2/129a4fd3` - mkv still can't be played.

`The media could not be loaded, either because the server or network failed or because the format is not supported.`

**Comment by Aniumbott** [comment]
> `File Browser v2.31.2/129a4fd3` - mkv still can't be played.
> 
> `The media could not be loaded, either because the server or network failed or because the format is not supported.`

Still facing the same issue in `v2.40.0/545c9722`, In some cases it plays audio only.
