### ISSUE TITLE
Filebrowser behind Nginx reverse proxy doesn't work

### ISSUE THREAD

**Issue by lewisxy** [filebrowser/filebrowser#400]
I use file browser behind the nginx reverse proxy, but it doesn't work.
The browser gets stuck on the bootstrapping page (with three dots)
Seems like the URL rewrite is problematic as it is requesting files like `https://static/js/app.525dfb941209c3761ba2.js` instead of my domain name.
Here are the errors from chrome dev console:
```
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
app.525dfb941209c3761ba2.js:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
manifest.613339d227475c6e6bcf.js:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
(index):1 Error during service worker registration: DOMException: Failed to register a ServiceWorker: The origin of the provided scriptURL ('https://sw.js') does not match the current origin ('https://files.myhost.com').
(anonymous) @ (index):1
static/img/icons/favicon-32x32.png:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
static/img/icons/favicon-16x16.png:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
```
Here is my `config.json` for filebrowser:
```
{
  "port": 8082,
  "noAuth": false,
  "baseURL": "/",
  "address": "127.0.0.1",
  "alternativeReCaptcha": false,
  "reCaptchaKey": "",
  "reCaptchaSecret": "",
  "database": "/etc/filebrowser/database.db",
  "log": "stdout",
  "plugin": "",
  "scope": ".",
  "allowCommands": true,
  "allowEdit": true,
  "allowNew": true,
  "commands": [
    "wget"
  ]
}
```
Here is my Nginx config file:
```
server {
    add_header Strict-Transport-Security max-age=63072000;
    add_header X-Frame-Options DENY;

    server_name files.myhost.com;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    listen 443;

    ssl on;
    ssl_certificate /root/ssl/chained.pem;
    ssl_certificate_key /root/ssl/domain.key;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK;
    ssl_session_cache shared:SSL:50m;
    ssl_prefer_server_ciphers on;
    ssl_dhparam /root/ssl/dhparam.pem;

    location / {
        client_max_body_size                    2048m;
        #proxy_set_header                        X-Forwarded-Host $host;
        #proxy_set_header                        X-Forwarded-Server $host;
        #proxy_set_header                        X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_http_version                      1.1;
        #proxy_set_header                        Upgrade $http_upgrade;
        #proxy_set_header                        Connection "upgrade";
        proxy_pass                              http://127.0.0.1:8082;
    }
}
```

**Comment by lewisxy** [comment]
Fixed with following nginx config file
```
server {
    add_header Strict-Transport-Security max-age=63072000;
    #add_header X-Frame-Options DENY;

    server_name files.myhost.com;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    listen 443;

    ssl on;
    ssl_certificate /root/ssl/chained.pem;
    ssl_certificate_key /root/ssl/domain.key;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK;
    ssl_session_cache shared:SSL:50m;
    ssl_prefer_server_ciphers on;
    ssl_dhparam /root/ssl/dhparam.pem;

    location / {
        client_max_body_size                    2048m;
        proxy_read_timeout                      86400s;
        proxy_send_timeout                      86400s;
        proxy_set_header                        X-Forwarded-Host $host;
        proxy_set_header                        X-Forwarded-Server $host;
        proxy_set_header                        X-Real-IP $remote_addr;
        proxy_set_header                        Host $host;
        proxy_set_header                        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version                      1.1;
        proxy_redirect                          off;
        proxy_set_header                        Upgrade $http_upgrade;
        proxy_set_header                        Connection "upgrade";
        proxy_pass                              http://127.0.0.1:8082;
    }
}
```

**Comment by 84ace** [comment]
This didn't work for me, all i ended up needed was to set the --baseurl option (--baseurl /filebrowser), as the reverse proxy config i have pointed it at http://site/filebrowser rather than http://site

**Comment by Darkham42** [comment]
I've the same issue...

I launch filebrowser with : 
`./filebrowser -c filebrowser.json`

My filebrowser.json : 
```json
{
  "port": 60605,
  "noAuth": false,
  "alternativeReCaptcha": false,
  "reCaptchaKey": "",
  "reCaptchaSecret": "",
  "baseURL": "/",
  "address": "127.0.0.1",
  "database": "/opt/filebrowser/filebrowser.db",
  "log": "stdout",
  "plugin": "",
  "scope": "/var/www/files/",
  "allowCommands": true,
  "allowEdit": true,
  "allowNew": true,
  "commands": [
    "git",
    "svn",
    "ls",
    "wget"
  ]
}
```

and my nginx conf for my subdomain : 
```conf
upstream filebrowser{
    server 127.0.0.1:60605;
}

server {
    listen      80;
    listen [::]:80;

    server_name files.domain.com;

    include conf.d/_letsencrypt;

    location / {
        return 301 https://files.domain.com$request_uri;
    }
}

server {
	listen      443 ssl http2;
	listen [::]:443 ssl http2;

	add_header Access-Control-Allow-Origin $http_origin;
	server_name files.domain.com;

	location / {
        	proxy_pass http://filebrowser;
   	}

  	error_log /var/log/nginx/files-error.log;
	access_log off;

	# SSL
}
```

I've tried what's above and still have the same errors as @lewisxy, anyone have an idea ?

**Comment by Darkham42** [comment]
Thanks to @hacdias I've found the error...

In my json config file : 
```json
"baseURL": "",
```

And it's working right now ! Thanks a lot.

**Comment by kawav** [comment]
I have the same issue and I resolve it.
If your nginx :
```
location /myfilebrowser {
        	proxy_pass http://127.0.0.1:12345;
   	}
```
Then :
```
"baseURL": "/myfilebrowser",
```
And it's working ! Thank to @84ace .

**Comment by mphz** [comment]
> Thanks to @hacdias I've found the error...
> 
> In my json config file :
> 
> ```json
> "baseURL": "",
> ```
> 
> And it's working right now ! Thanks a lot.

hi, should use "baseURL": "/" or "baseURL": ""

**Comment by mphz** [comment]
> I have the same issue and I resolve it.
> If your nginx :
> 
> ```
> location /myfilebrowser {
>         	proxy_pass http://127.0.0.1:12345;
>    	}
> ```
> 
> Then :
> 
> ```
> "baseURL": "/myfilebrowser",
> ```
> 
> And it's working ! Thank to @84ace .

hi, not working for me, stuck on loading 3 dots, f12 console all 200, looks fine, but just cannot show login page

**Comment by kawav** [comment]
> > I have the same issue and I resolve it.
> > If your nginx :
> > ```
> > location /myfilebrowser {
> >         	proxy_pass http://127.0.0.1:12345;
> >    	}
> > ```
> > 
> > 
> > Then :
> > ```
> > "baseURL": "/myfilebrowser",
> > ```
> > 
> > 
> > And it's working ! Thank to @84ace .
> 
> hi, not working for me, stuck on loading 3 dots, f12 console all 200, looks fine, but just cannot show login page


My config :
```
➜  cat .filebrowser.json
{
  "port": 8888,
  "baseURL": "/myfilebrowser",
  "address": "127.0.0.1",
  "log": "stdout"
}


➜  cat /etc/nginx/conf.d/default.conf
server  {
        listen 443 ssl http2;
        ssl on;
        ssl_certificate       /certificate.crt;
        ssl_certificate_key   /certificate_key.key;
        ssl_protocols         TLSv1.2 TLSv1.3;
        server_name     filebrowser.domain;

        location /myfilebrowser { #Same with the baseURL of .filebrowser.json
        proxy_redirect off;
        proxy_pass http://127.0.0.1:8888;
        #proxy_http_version 1.1;
        client_max_body_size 0;
        proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        }
}
```

Maybe it can help you.

**Comment by TCB13** [comment]
This works for me:

```
# Filebrowser
location / {
    proxy_redirect off;
    client_max_body_size 0;
    proxy_request_buffering off;
    proxy_pass http://127.0.0.1:4100;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

**Comment by freefurie** [comment]
Been getting the dreaded infinite loading circles as well, using nginx and docker to run filebrowser.

I do get 404's in the console on the "/static" files, implying it can't fetch them and thus infinitely load?

It tries to GET from "https://my.domain.com/static/css/app.1fbedfd4.css" and others. Anything I forgot to configure to make these static files accessible?

**Comment by mersinvald** [comment]
@freefurie did you find a solution? I'm facing the same with the latest docker image, the baseurl is set in the config (as confirmed by the log), but I get infinite loading and 404s on /static/... in browser logs.

**Comment by freefurie** [comment]
> [@freefurie](https://github.com/freefurie) did you find a solution? I'm facing the same with the latest docker image, the baseurl is set in the config (as confirmed by the log), but I get infinite loading and 404s on /static/... in browser logs.

I didn't get it working and kind of forgot about doing anything with it, sorry :(

**Comment by notTPALT** [comment]
> ```
> location /myfilebrowser {
>         	proxy_pass http://127.0.0.1:12345;
>    	}
> ```
> 
> Then :
> 
> ```
> "baseURL": "/myfilebrowser",
> ```
>

I tried this and it works, but I don't get why it is working. Every other app I'm currently running on my server has both of those set to the same path, e.g. if ` location /abc/ { proxy_pass http://domain.com:port/abc/; }` then `baseURL=/abc/`. Only this app is different.
