### ISSUE TITLE
BaseUrl not longer honored when in url of static assets

### ISSUE THREAD

**Issue by bcardiff** [filebrowser/filebrowser#522]
In v1.10.0 I was able to use `--baseurl` to host the FB in a specific route.
In master I am not able longer to do that because the url of the assets does not include baseurl and are linked from root.

With v1.10.0 (right behavior):

```
$ docker run --rm -p 8080:80 filebrowser/filebrowser:v1.10.0 --baseurl /b --port 80
$ curl localhost:8080/b
... <script type=text/javascript src="/b/static/js/app.c9e23184bf5593511600.js"></script>
```

With latest (broken):

```
$ docker run --rm -p 8080:80 filebrowser/filebrowser:latest --baseurl /b --port 80
$ curl localhost:8080/b
... <script type=text/javascript src="/static/js/app.c9e23184bf5593511600.js"></script>
```

browser will request the invalid url `localhost:8080/static/js/app.c9e23184bf5593511600.js`

**Comment by eine** [comment]
@bcardiff thanks for reporting! It is fixed now.

@hacdias, the underlying issue was that in #506 all the config keys where lowercased, in order to have them automatically identified by `viper.BindPFlags`. However, I forgot to change them in the frontend. Therefore, the fix to this issue was to rename `BaseURL` in `frontend/build/config.js`: https://github.com/filebrowser/frontend/commit/3ae9e518a30ec59e307f60f0225b8eb04433be08. Can you think of any other similar required modification off the top of your head?

**Comment by bkanuka** [comment]
FYI the latest docker image created Sep 8 still does not have this fix.

**Comment by eine** [comment]
I just tested it, and it works for me:

``` bash
docker pull filebrowser/filebrowser
docker run --rm -it -p 5555:8000 filebrowser/filebrowser -b /admin -p 8000
```

Then, browse `localhost:5555` or `curl localhost:5555/admin`.

**Comment by bkanuka** [comment]
You're right - the html returned by curl has the correct urls. The problem now is that not all the code from the js has the right url basename.  I'll find an example...

**Comment by bkanuka** [comment]
![screenshot from 2018-09-25 18-16-43](https://user-images.githubusercontent.com/2676579/46046631-c9ca5f80-c0ef-11e8-9a6f-e5b76c82524e.png)

So when I go to http://mydomain.com/files  I'm redirected to http://mydomain.com/login?redirect=%2Ffiles%2F  plus of course all the 404's you see on the debug panel - every 404 is because there's a request being sent without the `files/` base directory.

I too am running with docker and passing `-b /files` at the command.

**Comment by bkanuka** [comment]
The fix should be just search for every instance of [BaseURL](https://github.com/filebrowser/frontend/search?q=BaseURL) in the frontend code and replace it with `baseurl`.

I would do this, but I know so little about Go and the frameworks used here. No idea how to even test this.

**Comment by eine** [comment]
@bkanuka, you are ok. I did not replace it properly in all the javascript sources. As you say, `BaseURL` should be replaced with `baseurl`.

In order to test the fix, please see [filebrowser/community](https://github.com/filebrowser/community). There you will find instructions about how to build the frontend first, then the backend and, last, test it all. For a quicker path, see https://github.com/filebrowser/community/blob/master/development.md.

**Comment by bkanuka** [comment]
Okay - thanks for all the documentation!  Quick question: is there a `Dockerfile` that builds the whole thing? Rather than building on the host and moving the binary to the docker.

**Comment by eine** [comment]
@bkanuka we do not provide a file that does everything at once. But we provide a development docker image (`filebrowser/dev`) that can be used to build both the frontend and the backend, without installing any dependency in the host:

``` bash
USE_DOCKER="true" ./build/build_all.sh
docker build -t filebrowser/filebrowser .
```

See https://github.com/filebrowser/community/blob/master/development.md#docker-and-shell.

So, you can use `build_all.sh` and extend the reference Dockerfile to a multistage dockerfile if you wish:

```
FROM filebrowser/dev AS build
RUN git clone --recurse-submodule https://github.com/filebrowser/filebrowser && \
 cd filebrowser && \
 ./build/build_all.sh && \
  mv filebrowser /tmp

FROM scratch

COPY --from=filebrowser/dev /tmp/filebrowser /filebrowser
COPY --from=filebrowser/dev /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

VOLUME /tmp
VOLUME /srv
EXPOSE 80

COPY Docker.json /.filebrowser.json

ENTRYPOINT ["/filebrowser"]
```

**Comment by HeavyHorst** [comment]
I executed "find -type f -exec sed -i 's/BaseURL/baseurl/g' {} \;" in the frontend folder and then recreated the assets with "build/build_assets.sh ". After that everything seems to work again.

**Comment by eine** [comment]
@HeavyHorst thanks for reporting. Would you like to open a PR with those changes?

**Comment by eine** [comment]
Thanks to @HeavyHorst's contribution (filebrowser/frontend#40), this should be fixed now. So, I'm closing this issue.

Nevertheless, note that building the backend with latest dependencies is failing ATM (see #554). Should you want to try this fix, you need to build the assets only.
